name: Deploy HTML to GitHub Pages

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main  # promeni ako ti je glavni branch drugi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Preuzmi repo
      - uses: actions/checkout@v3

      # 2️⃣ Deploy na GitHub Pages
      - uses: actions/deploy-pages@v4
