name: Deploy Airsoft HTML

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main  # ili tvoj glavni branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Deploy na GitHub Pages
      - uses: actions/deploy-pages@v4
        with:
          folder: '.'  # jer je airsoft.html u root-u
